# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloak" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8ef88691445c7fb0c09cd5429e0f09a36121c7a58ea98d0075dd910b3c988ba7"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8cfb3141ece3ef4b917e8cbc1a93de4190c9daff327145e1d1fa02e5c68f4c8"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aef374e19f414004d6685bf8be0bef6a382b25e89458da0e09610d67027d4d3a"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "17e0f2d7a03f73d5f549228a8aae1fb42cfe8ed39fab4ce08a26339e61f10ffe"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cloak"
  desc "Hand AI agents fake credentials; keep the real ones out of their context"
  homepage "https://github.com/hoophq/cloak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloak"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cloak")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloak"]
    end
  end

  # No zap stanza required

end
