# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloak" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "ba32f18d44c1f76f5d97a77b1091a1034d7859c196f4bee1e67c5c5def0953c7"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01154d67db716cdd037d47f1bdb01b5f3f24aeed7166615db4d4a694d05d54ed"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "191d49d331c13daa69e432874d2dfa16b49b055149457e0ed40d2e47155d4510"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eaac306407fb6ef53f100313c99d84b3e465077b21fcdf038add2eb935a0840b"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cloak"
  desc "Hand AI agents fake credentials; keep the real ones out of their context"
  homepage "https://github.com/hoophq/cloak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloak"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cloak")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloak"]
    end
  end

  # No zap stanza required

end
