# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloak" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "7827834e054f28017c77b72b51d9c74a9156477b2f5e0249f75416773c796d3d"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "290cda1b412bb27d789d5a2397e620de066b9c61aa07e546e3d64e8f80a5847f"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f98a7434cd9ff2066591aa2d58b960c8c377248aafb7d7c6d5cb6d0d587475df"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86ca9ff2c2bffcecef01b2c2e86816b99b60c52b7551889daf687ea8fcb76242"
      url "https://github.com/hoophq/cloak/releases/download/v#{version}/cloak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cloak"
  desc "Hand AI agents fake credentials; keep the real ones out of their context"
  homepage "https://github.com/hoophq/cloak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloak"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/cloak")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloak"]
    end
  end

  # No zap stanza required

end
