# This file was generated by GoReleaser. DO NOT EDIT.
cask "fence" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "7d98c4e9c57259171c1e510b5d1147e1d39911e751ad7bfa313ca7dbded0d1a9"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec293a4b5f81721bb0a8b018e5a325befb8ed4ec1d47c6b4fa719e5c949cd889"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86f4e09dba44d193a3218feb4c258d39859d78d323b081557bc47b9cb972fbce"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5036135bafbdfcaf69cfc2a7f39b7e60a40cb23b36fe2798e766be3c624d24e"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fence"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/fence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fence"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fence"]
    end
  end

  # No zap stanza required

end
