# This file was generated by GoReleaser. DO NOT EDIT.
cask "fence" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "e4a5fc21b35a3a662653cfbec713627f99af2c33e7f2c558e458a8d0b67aae09"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8c74ae66d00103cfed94b7f9248611b3418249f25c91095bf637c4c2b894664"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c0c1f6543d802cf1cf874afcd76abbd4f8fa7934a6180ba99e6299e93042e26"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffaa0168e0400dcfaed7c658d255f6692c8732ec48e9fa9670c1d3f6010b68f7"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fence"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/fence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fence"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fence"]
    end
  end

  # No zap stanza required

end
