# This file was generated by GoReleaser. DO NOT EDIT.
cask "fence" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "ef82be4226e24fba3f4ee31a45f7fcf1f53667e736de92f56a7bac65bbf81543"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35bf4542751631284017101a9cee2810f652da1a978717d687ebef5db218fccc"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "794ae4530c8936d70a2d3e68348bd665d09820a8cf82ac30dc339fb2ef8996fc"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35248b26daa6fd336f2941ff697429af7da72e6120ba4b0e74d23996a63e9be9"
      url "https://github.com/hoophq/fence/releases/download/v#{version}/fence_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fence"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/fence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fence"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fence"]
    end
  end

  # No zap stanza required

end
