# This file was generated by GoReleaser. DO NOT EDIT.
cask "julius" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "c7b2b0c5d0487df01c3da9d7f3b21847f2594bdf56431c498656738ad53a8ccf"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0257ad3471406a318f3fe910a5fedcc5d9b13ee12df389bbdc590a4e603f1f73"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df994171ee90fb7e13a0041e08ecb757afa254641583dca16e302827a9498f71"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2146c79af8477787024a5f8b1f3c15eafbb957a136d354fbce8fec3e90c2bd67"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_arm64.tar.gz"
    end
  end

  name "julius"
  desc "Cut LLM token usage on command output and API traffic"
  homepage "https://github.com/hoophq/julius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "julius"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/julius"]
    end
  end

  # No zap stanza required

end
