# This file was generated by GoReleaser. DO NOT EDIT.
cask "julius" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "0584ceb6115297164db674678dc7a906eaf9df4d6e8e056bf9783ef344249c9d"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd8dd2f308e446c91e6537a2d5bbb47ab23b9778934cbc8c8e114e085083e482"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a3f52427d3b142907d8b7b6a0fe35a9162fb73a8e52bfa5778cc491c3084583"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dfd0d5eb7664a29fc0d5576c2330113558eb0ba3fa896f220513d4b2ed81bf9"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_arm64.tar.gz"
    end
  end

  name "julius"
  desc "Cut LLM token usage on command output and API traffic"
  homepage "https://github.com/hoophq/julius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "julius"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/julius"]
    end
  end

  # No zap stanza required

end
