# This file was generated by GoReleaser. DO NOT EDIT.
cask "julius" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "e363465bd34b0bdd16bdd0bb833c5d4b8f03f9de40d59fb42b390fc6c887ad0f"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "949ae7bea54dd4ecf5be88b0f0b3553406e0df06572f672952a81c6e6d4d9a70"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c21775b8e1ed7ef2627bc74f897a10dac01a3af680efc7de892741fa510a264"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d59314efec01e95969a8d687dba03e3eb49a2b4d6852b11bf6a9aa5cf52f3b0"
      url "https://github.com/hoophq/julius/releases/download/v#{version}/julius_#{version}_linux_arm64.tar.gz"
    end
  end

  name "julius"
  desc "Cut LLM token usage on command output and API traffic"
  homepage "https://github.com/hoophq/julius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "julius"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/julius"]
    end
  end

  # No zap stanza required

end
