# This file was generated by GoReleaser. DO NOT EDIT.
cask "leash" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1abeb419812ffbc2cbd42a9d96d93ecd341959ac5bbf6451c03c3892b0f47c1a"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "86f94f8a943422275b0f1519eefd7c961eeba57fc4d3f863906df22db5f4a34e"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3ec3d8d58ff4795b103ce14dc6cf1b9b5fec2da99234fc78f44f7661f167b14"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0744217709a2cf97707ef7571df497ef37f8a954bab25e86c0777bdf719ea1fa"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leash"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/leash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leash"]
    end
  end

  # No zap stanza required

end
