# This file was generated by GoReleaser. DO NOT EDIT.
cask "leash" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "f69be5b1f1bb5b0b3fffac3e0e8d9e4d4c67e388f13e60cfcbf846943816611b"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8cacb4b56dc65bfc42030ee2cf6243948c5d9e08d5e2020b854a0338a66c7a99"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b352ab2d938ab3e1eae65b10207988319da9bf47c4acf45abb0f5558c4ef479b"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d400a7bbcc33dca5da3cf4e216939254f45d40e1b6e4bf963bb28bf359301c7"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leash"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/leash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leash"]
    end
  end

  # No zap stanza required

end
