# This file was generated by GoReleaser. DO NOT EDIT.
cask "leash" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9d7712df3eccabd4132bbb6dedd05750a2e50312361f78abadd940c84d063800"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "73944c873c859983dc65a6d0f60a035ce03406242bfbef8130db31e43699e09f"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fc66a1d17a7b687d49b7dae8f0b13eafc7aaa6f9c7e6a8b00b461212e97b6cf"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "03c693bb02130e40071508f8824047081ccda15962f7148963e1950d428aeb18"
      url "https://github.com/hoophq/leash/releases/download/v#{version}/leash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leash"
  desc "Guardrails for AI coding agents — blocks catastrophic tool calls before they run"
  homepage "https://github.com/hoophq/leash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leash"]
    end
  end

  # No zap stanza required

end
