# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blueprint < Formula
  desc "Read-only census of what you run on AWS, and what AWS charged for it"
  homepage "https://github.com/hoophq/blueprint"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/blueprint/releases/download/v0.4.0/blueprint_0.4.0_darwin_amd64.tar.gz"
      sha256 "9c2e3233e17ae4e061fe5872ad8791d9c11ded11a3ff4268844bd41125b38ea9"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hoophq/blueprint/releases/download/v0.4.0/blueprint_0.4.0_darwin_arm64.tar.gz"
      sha256 "ad446f4b203aa3fa4b4dd02bdab4965c6fa40465bb77f8464e982be08fedf925"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/blueprint/releases/download/v0.4.0/blueprint_0.4.0_linux_amd64.tar.gz"
      sha256 "ec690c96b0da89b7aaee3511cb79705b0f99a091d40b90569bf889d1d68663cd"
      define_method(:install) do
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/blueprint/releases/download/v0.4.0/blueprint_0.4.0_linux_arm64.tar.gz"
      sha256 "c29f9090f427807feb6d9039e8a8074db3d56610a12e8297b6cd638957bfaeb2"
      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  test do
    system "#{bin}/blueprint", "--version"
  end
end
