# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blueprint < Formula
  desc "Read-only census of what you run on AWS, and what AWS charged for it"
  homepage "https://github.com/hoophq/blueprint"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hoophq/blueprint/releases/download/v0.3.0/blueprint_0.3.0_darwin_amd64.tar.gz"
      sha256 "7e2fc55d731ede9e62f80ad400d7e5211cec2eb5c2ff99acd4bad015cdfab4dc"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hoophq/blueprint/releases/download/v0.3.0/blueprint_0.3.0_darwin_arm64.tar.gz"
      sha256 "c067d5c034306212eb5622bf2580cb9c079ca8fe2479cf2750577df2b5ce71ee"

      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/blueprint/releases/download/v0.3.0/blueprint_0.3.0_linux_amd64.tar.gz"
      sha256 "3297fb84fc61c66a1315f8a559634e60b1750638960b4f6b493903ccb73d948a"
      define_method(:install) do
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoophq/blueprint/releases/download/v0.3.0/blueprint_0.3.0_linux_arm64.tar.gz"
      sha256 "ffa87db2dc5870bd8ac24c62a3fcbb612c65af6b49bd4130915f97f6403e8504"
      define_method(:install) do
        bin.install "blueprint"
      end
    end
  end

  test do
    system "#{bin}/blueprint", "--version"
  end
end
